name : Reach The Border
brand : Reach The Border
description : Something Something about latvian youth exchange
keyword : 
url : http://rich0664.github.io/ReachTheBorder/
baseurl : /ReachTheBorder
permalink: /blog/:title



email : rich0664@gmail.com
twitter : 
github : rich0664
author : Richard Sööt
year : 2015
markdown : kramdown
exclude :
  - node_modules



paginate: 5
paginate_path: "/blog/page:num/"
excerpt_separator: "<!–-break-–>"


prose:
  rooturl: '_posts'
  siteurl: 'http://rich0664.github.io/ReachTheBorder/'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "title"

